name: neostar
region: nyc
services:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: starse-git/NeoStar
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
    http_port: 3000
    routes:
      - path: /
